### ISSUE TITLE
ReadMe Improvements.

### ISSUE THREAD

**Issue by JasonHoku** [Buuntu/fastapi-react#114]
Can the readme.md reflect the coockiecutters pip reccomended setup?

 Is it for a python3 venv or a redirected path for python3? I went with pip3 install

Secondly, can we have more info on "docker-compose up -d" seems to not work intuitively, requiring un-listed documentation:

Suggested by CLI all run errors:
docker-machine start default
docker-machine create

until finally (maybe add documentation to this step)': 
docker-machine create none

Oh, no that didn't do anything either. :(

It was sudo docker-compose up -d

Maybe more clarity for the docker-compose installation or maybe my cookiecutter setup was wrong?

Either way, excited to see this powerful tech here educating <3 Thank you!

**Comment by JasonHoku** [comment]
One more point to add to this after a clean attempt from a fresh Ubuntu 20.04 LTS VM reaveals:

pip install cookiecutter should be:
python3 pip install cookiecutter

and

cookiecutter gh:Buuntu/fastapi-react should be:
python3 -m cookiecutter gh:Buuntu/fastapi-react


To account for ease of setup on more global/cross-platform path variables.

**Comment by Buuntu** [comment]
I think you're right about the python/cookiecutter instructions.  As for docker-compose, I would prefer to just link to docker-compose documentation since training people how to use Docker is kind of outside of the scope of this project.  `sudo` could be helpful but that is also platform dependent, since Windows users would not use sudo.  You shouldn't need anything with `docker-machine` though, not sure where you read that?

Anyway I would accept a PR for this @JasonHoku or I can get to it sometime next week if you're not up for it.

**Comment by JasonHoku** [comment]
I'm up for it!

The docker-machine codes come from trying ti run 
docker-compose up -d
the error says VM not found (If I remember correctly) and then echoes to try using this:
docker-machine start default
which then echoes that there is no default machine and to use this:
docker-machine create

Works successfully after creating a machine.

I am shooting a recording of a fresh install of this application on a fresh Ubuntu VM here in an hour, and will clarify the details before making this PR. Thank you again, Buuntu, amazing work here!  :^)

**Comment by JasonHoku** [comment]
Thank you so much for the opportunity! 

Clarified and double checked. :

https://github.com/Buuntu/fastapi-react/pull/115

**Comment by Buuntu** [comment]
Closed by #115
