### ISSUE TITLE
Scripts fail with version issues on backend

### ISSUE THREAD

**Issue by lucabotti** [Buuntu/fastapi-react#150]
while trying to build the backend:

`INFO: pip is looking at multiple versions of celery to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of bcrypt to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of authlib to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of alembic to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 3) and starlette==0.13.8 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested starlette==0.13.8
    fastapi 0.61.1 depends on starlette==0.13.6

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
ERROR: Service 'backend' failed to build : The command '/bin/sh -c pip install --no-cache-dir -r requirements.txt' returned a non-zero code: 1

**Comment by gmagno** [comment]
I also hit this issue.
Dirty and temporary solution: loosen the `requirements.txt` constraints, for instance by removing versions altogether.

**Comment by rbracco** [comment]
**Solution:** Remove starlette from backends/requirements.txt. Starlette is a dependency of fastapi so installing fastapi 0.61.1 will automatically choose the correct version of starlette. Alternatively you can change the starlette line to `starlette==0.13.8`

**More Details**: 
This error is due to fastapi using starlette as a dependency. Fastapi 0.61.1 expects starlette 0.13.6 but the requirements.txt specifies starlette==0.13.8 and since the requirements.txt is using exact versions (==), pip can't resolve the conflict.

**Comment by Buuntu** [comment]
Sorry for the delay, I went ahead and updated FastAPI and removed starlette as @rbracco suggested.  Give it a try now.
